/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desas;

/**
 *
 * @author user
 */
public class DesasGui extends javax.swing.JPanel {
    
    private String firstMove = "X";

    /**
     * Creates new form DesasGui
     */
    public DesasGui() {
        //initComponents();
        //setSize(600, 600); //nedarbojas, jo nezinu kur likt - speles loga izmers. It ka jaliek seit bet nestrada
        //  setLocationRelativeTo(null); //nedarbojas, jo nezinu kur likt - pop-up japaradas centra
    }
    private void whosFirst(){
    
        if(firstMove.equalsIgnoreCase("X"))
        {
            firstMove = "0";
        }else{
            firstMove = "X";
        }
        
    }
    
    private void XWon(){
        System.out.println("X player won");
    }
    
    private void OWon(){
            System.out.println("O player won");
    }
    
    private void winCombos() {
        
        String one = jButton1.getText();
        String two = jButton2.getText();
        String three = jButton3.getText();
        String four = jButton4.getText();
        String five = jButton5.getText();
        String six = jButton6.getText();
        String seven = jButton7.getText();
        String eight = jButton8.getText();
        String nine = jButton9.getText();
        
        
       if(one == "X" && two == "X" && three == "X");
        {
            XWon();
        
        if(four == "X" && five == "X" && six == "X");
        {
            XWon();
        }
            if(seven == "X" && eight == "X" && nine == "X");
        {
            XWon();
        }
            if(one == "X" && four == "X" && seven == "X");
        {
            XWon();
        }
            if(two == "X" && five == "X" && eight == "X");
        {
            XWon();
        }
            if(three == "X" && six == "X" && nine == "X");
        {
            XWon();
        }
            if(one == "X" && five == "X" && nine == "X");
        {
            XWon();
        }
            if(three == "X" && five == "X" && three == "X");
        {
            XWon();    
    }
        }
        
        //0Won
        
    if(one == "0" && two == "0" && three == "");
        {
            XWon();
        
        if(four == "0" && five == "0" && six == "0");
        {
            OWon();
        }
            if(seven == "0" && eight == "0" && nine == "0");
        {
            OWon();
        }
            if(one == "0" && four == "0" && seven == "0");
        {
            OWon();
        }
            if(two == "0" && five == "0" && eight == "0");
        {
            OWon();
        }
            if(three == "0" && six == "0" && nine == "0");
        {
            OWon();
        }
            if(one == "0" && five == "0" && nine == "0");
        {
            OWon();
        }
            if(three == "0" && five == "0" && three == "0");
        {
            OWon();    
    }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2_GridLayout = new javax.swing.JPanel();
        jPanel2_1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3_2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4_3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel5_4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6_5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel7_6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel8_7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel9_8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel10_9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();

        setToolTipText("Desas");
        setName("Desas"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Place Holder");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel2_GridLayout.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2_GridLayout.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        jPanel2_1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2_1.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2_1.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel2_1);

        jPanel3_2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_2.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3_2.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel3_2);

        jPanel4_3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4_3.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4_3.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel4_3);

        jPanel5_4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5_4.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5_4.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel5_4);

        jPanel6_5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6_5.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6_5.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel6_5);

        jPanel7_6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7_6.setLayout(new java.awt.BorderLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7_6.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel7_6);

        jPanel8_7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8_7.setLayout(new java.awt.BorderLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8_7.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel8_7);

        jPanel9_8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9_8.setLayout(new java.awt.BorderLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9_8.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel9_8);

        jPanel10_9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10_9.setLayout(new java.awt.BorderLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel10_9.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel2_GridLayout.add(jPanel10_9);

        jPanel1.add(jPanel2_GridLayout, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton5.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       jButton8.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jButton9.setText(firstMove);
        whosFirst();
        winCombos();
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10_9;
    private javax.swing.JPanel jPanel2_1;
    private javax.swing.JPanel jPanel2_GridLayout;
    private javax.swing.JPanel jPanel3_2;
    private javax.swing.JPanel jPanel4_3;
    private javax.swing.JPanel jPanel5_4;
    private javax.swing.JPanel jPanel6_5;
    private javax.swing.JPanel jPanel7_6;
    private javax.swing.JPanel jPanel8_7;
    private javax.swing.JPanel jPanel9_8;
    // End of variables declaration//GEN-END:variables
}
